version: '3'

services:

    frontend:
        build: frontend/.
        container_name: frontend
        ports: 
            - '80:80'
        volumes:
            - '.:/frontend/app'
        networks: 
            app-net:
                ipv4_address: 192.168.0.2

    backend:
        build: backend/.
        container_name: backend
        ports: 
            - '3000:3000'
        volumes:
            - '.:/backend/app'
        networks: 
            app-net:
                ipv4_address: 192.168.0.3

    database:
        image: mysql:latest
        
        container_name: database
        ports: 
            - '3306:3306'
        environment: 
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: AYD1
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - database:/var/lib/mysql
        networks: 
            app-net:
                ipv4_address: 192.168.0.4

networks:
    app-net:
        ipam:
            driver: default
            config:
            - subnet: "192.168.0.0/24"

volumes:
    database: